### PR TITLE
fix: fix submit job show timestamp

### LINKED ISSUE #2750: after submitting a job, the `start_time` is still not human-readable
after submitting a new job, the `start_time` of the job info is still not human-readable (the format for `show jobs` has been fixed)

image

### PR DESCRIPTION
**Pull request by tobegit3hub**
* Resolve https://github.com/4paradigm/OpenMLDB/issues/2750 .

Screen Shot 2022-11-02 at 11 33 22

### CODE REVIEW

File: src/sdk/sql_cluster_router.cc [hunk 1]
```diff
@@ -4178,5 +4131,25 @@ void SQLClusterRouter::ReadSparkConfFromFile(std::string conf_file_path, std::ma
...
+        return {};
+    }
+    if (rs->Size() == 0) {
+        status.code = ::hybridse::common::StatusCode::kCmdError;
+        status.msg = "Job not found: " + std::to_string(job_id);
+        return {};
+    }
+    if (FLAGS_role == "sql_client") {
+        return std::make_shared<ReadableResultSetSQL>(rs);
+    }
```
Comment (tobegit3hub) [inline src/sdk/sql_cluster_router.cc:4260]: else return original rs.

File: src/sdk/sql_cluster_router.cc [hunk 2]
```diff
@@ -2684,11 +2652,7 @@ std::shared_ptr<hybridse::sdk::ResultSet> SQLClusterRouter::ExecuteSQL(
                     base_status = ImportOfflineData(sql, config, database, is_sync_job, offline_job_timeout, &job_info);
                 }
                 if (base_status.OK() && job_info.id() > 0) {
-                    std::stringstream ss;
-                    ::openmldb::cmd::PrintJobInfos({job_info}, ss);
```
Comment (tobegit3hub) [inline src/sdk/sql_cluster_router.cc:2691]: Remove PrintJobInfos.

**Review by dl239 — APPROVED** [review]

**Review by lqy222 — APPROVED** [review]
