### PR TITLE
fix: add udf for string to timestamp and ut

### LINKED ISSUE #3012: Select timestamp(string_val) will get null data
**Bug Description**

Select timestamp(string_val) will get null data which is inconsistent with online engine.

**Expected Behavior**

Get valid data.

### PR DESCRIPTION
**Pull request by tobegit3hub**
* Resolve https://github.com/4paradigm/OpenMLDB/issues/3012 .

### CODE REVIEW

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/ConstProjectPlan.scala [hunk 1]
```diff
@@ -66,9 +67,24 @@ object ConstProjectPlan {
...
 
+  def stringToTimestamp: String => Timestamp = (input: String) => {
+    if (input == null) {
+      null.asInstanceOf[Timestamp]
+    } else {
+      val stringPattern = input.length match {
+        case 19 => "yyyy-MM-dd HH:mm:ss"
+        case 10 => "yyyy-MM-dd"
+        case 8 => "yyyyMMdd"
+        case _ => throw new Exception(s"Unsupported timestamp format for string $input")
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/ConstProjectPlan.scala]: return null instead of throwing exception.

File: java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/end2end/simple_project/TestStringToTimestamp.scala [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+    sess.registerTable("t1", df)
+
+    val sql = "SELECT cast(str_timestamp as timestamp) from t1"
+    val outputDf = sess.sql(sql)
+
+    val rows = outputDf.collect()
+    assert(Timestamp.valueOf("2022-01-22 0:0:0") == rows(0).getTimestamp(0))
+    assert(Timestamp.valueOf("2022-01-23 22:22:22") == rows(1).getTimestamp(0))
+    assert(Timestamp.valueOf("2022-01-24 0:0:0") == rows(2).getTimestamp(0))
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/end2end/simple_project/TestStringToTimestamp.scala:49]: Add case for incorrect string format like "2022".

**Review by dl239 — APPROVED** [review]

**Review by vagetablechicken — APPROVED** [review]
