### PR TITLE
fix: fix external udf for yarn mode

### LINKED ISSUE #2801: External UDF does not work for yarn-client and yarn-cluster for offline
We get the incorrect file path for yarn mode and do not register udf in driver when using yarn mode.

### PR DESCRIPTION
**Pull request by tobegit3hub**
* Resolve https://github.com/4paradigm/OpenMLDB/issues/2801 .

### CODE REVIEW

File: java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/spark/SparkJobManager.scala [hunk 1]
```diff
@@ -115,10 +116,21 @@ object SparkJobManager {
...
       launcher.setConf("spark.openmldb.offline.data.prefix", TaskManagerConfig.OFFLINE_DATA_PREFIX)
     }
 
+    // Set external function dir for offline jobs
+    val absoluteExternalFunctionDir = if (TaskManagerConfig.EXTERNAL_FUNCTION_DIR.startsWith("/")) {
+      TaskManagerConfig.EXTERNAL_FUNCTION_DIR
+    } else {
+      // TODO: The current path is incorrect if running in IDE, please set `external.function.dir` with absolute path
+      // Concat to generate absolute path
+      Paths.get(Paths.get(".").toAbsolutePath.toString, TaskManagerConfig.EXTERNAL_FUNCTION_DIR).toString
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/spark/SparkJobManager.scala:130]: Test with absoulte path.

**Review by dl239 — APPROVED** [review]

**Review by zhanghaohit — APPROVED** [review]
