### PR TITLE
fix: add more functions and unit tests for TaskManager Java SDK

### LINKED ISSUE #1009: Add more functions and unit tests for TaskManager Java SDK
Add more functions for Java SDK of TaskManager.

### PR DESCRIPTION
**Pull request by yabg-shuai666**
close #1009

### CODE REVIEW

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 1]
```diff
@@ -42,6 +45,8 @@
      * @param endpoint the endpoint of TaskManager server, for example "127.0.0.1:9902".
      */
     public TaskManagerClient(String endpoint) {
+
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java:46]: Remove these empty line.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 2]
```diff
@@ -57,62 +62,278 @@ public TaskManagerClient(String endpoint) {
...
+        if (response.getCode() != 0) {
+            String errorMessage = "Fail to request, code: " + response.getCode() + ", error: " + response.getMsg();
+            throw new Exception(errorMessage);
+        }
+        return response.getMsg();
+    }
+    /**
+     * RunBatchSql.
+     *
+     * @param sql,output_path.
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: This is not standard Java doc. It would be auto generated by IDE or change like others.

```
@param sql
@param output_path
```

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+public abstract class TaskManagerClient_Test {
+    @Ignore
+    @Test
+    public  void testTaskManagerClient() throws Exception{
+        TaskManagerClient client = new TaskManagerClient("127.0.0.1:9995");
+        client.showJobs();
+//        client.stopJob(21);
+        client.showBatchVersion();
+        client.showOneJob(21);
+        client.importOnlineData("show tables;");
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java]: These test SQL will always fail. Should provide the correct one for unit tests.

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+        client.importOnlineData("show tables;","1");
+//
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java]: Remove the debug string.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 5]
```diff
@@ -57,62 +62,278 @@ public TaskManagerClient(String endpoint) {
...
+     *
+     * @throws Exception
+     */
+    public String runBatchSql(String sql,String output_path)throws Exception {
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: We don't need to return the message as output of method.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 6]
```diff
@@ -57,62 +62,278 @@ public TaskManagerClient(String endpoint) {
...
+        TaskManager.ShowJobResponse response = taskManagerInterface.RunBatchSql(request);
 
+        if (response.getCode() != 0) {
+            String errorMessage = "Fail to request, code: " + response.getCode() + ", error: " + response.getMsg();
+            throw new Exception(errorMessage);
+        }
+        return response.getMsg();
+    }
+    /**
+     * RunBatchSql.
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Use one sentence to describe the method instead of just the method name.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 7]
```diff
@@ -57,62 +62,278 @@ public TaskManagerClient(String endpoint) {
...
+        return response.getJob();
+    }
+    /**
+     * ImportOnlineData
+     *
+     * @param sql .
+     *
+     * @throws Exception
+     */
+    public String importOnlineData(String sql) throws Exception {
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Reuse the method below `importOnlineData(String sql,String default_db)` by passing the parameters instead of copying the similar logic again.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 8]
```diff
@@ -57,62 +62,278 @@ public TaskManagerClient(String endpoint) {
...
+    }
+    /**
+     * DropOfflineTable
+     *
+     * @param sql .
+     *
+     * @throws Exception
+     */
+    public String dropOfflineTable(String sql) throws Exception {
+        TaskManager.ExportOfflineDataRequest request = TaskManager.ExportOfflineDataRequest.newBuilder()
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java:272]: This should be `dropOfflineTable` instead of `ExportOffline`

**Review by tobegit3hub — CHANGES_REQUESTED** [review]

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java (hunk 5 above)
Comment (tobegit3hub) [reply java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Return the job id.

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java [hunk 9]
```diff
@@ -0,0 +1,23 @@
+package com._4paradigm.openmldb.taskmanager;
+
+import com._4paradigm.openmldb.taskmanager.client.TaskManagerClient;
+import org.testng.annotations.Ignore;
+import org.testng.annotations.Test;
+
+
+public abstract class TaskManagerClient_Test {
```
Comment (aceforeverd) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java]: no underscore, Keep in mind the class name convention

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 10]
```diff
@@ -57,72 +61,276 @@ public TaskManagerClient(String endpoint) {
...
+        return response.getJob();
+    }
+    /**
+     * Import online data without default_db.
+     *
+     * @param sql query sql string.
+     * @throws Exception
+     */
+    public String importOnlineData(String sql) throws Exception {
+        String Msg = importOnlineData(sql, new HashMap<String, String>(), "");
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Return `importOnlineData(sql, new HashMap<String, String>(), "");` directly and do not need to use new variable `Msg`.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 11]
```diff
@@ -57,72 +61,276 @@ public TaskManagerClient(String endpoint) {
...
-        for (com._4paradigm.openmldb.proto.TaskManager.JobInfo jobInfo: jobInfos) {
+        for (TaskManager.JobInfo jobInfo: jobInfos) {
             System.out.println(jobInfo);
         }
     }
-
     /**
      * Submit job to show batch version.
-     * 
+     * @return job's id.
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: It would be better to change to `id of job`.

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java [hunk 12]
```diff
@@ -0,0 +1,22 @@
...
+import com._4paradigm.openmldb.taskmanager.client.TaskManagerClient;
+import org.testng.annotations.Ignore;
+import org.testng.annotations.Test;
+
+
+public abstract class TaskManagerClientTest {
+    @Ignore
+    @Test
+    public void TestManagerClient() throws Exception{
+        TaskManagerClient client = new TaskManagerClient("127.0.0.1:9995"); //要与taskmanager.properties里的配置一致
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java]: Remove the Chinese comment. Use English or just remove it.

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java [hunk 13]
```diff
@@ -0,0 +1,22 @@
...
+//        client.stopJob(0);传入job id
+        client.printJobs();
+        client.showJobs();
+        client.importOnlineData("load data infile '/Users/4paradigm/IdeaProjects/OpenMLDB/java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/test.csv' " +
+                "into table test_taskmanager.t3 options(format='csv', foo='bar', header=false, mode='append');");//插入需要大概半分钟左右的时间，注意最好不要在t1表上插入，否则会失败。
+        client.showJobs();
+        client.printJobs();
+        System.out.println(client.showBatchVersion());;
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java]: Remove the `System.out.println`.

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java [hunk 14]
```diff
@@ -0,0 +1,22 @@
...
+
+public abstract class TaskManagerClientTest {
+    @Ignore
+    @Test
+    public void TestManagerClient() throws Exception{
+        TaskManagerClient client = new TaskManagerClient("127.0.0.1:9995"); //要与taskmanager.properties里的配置一致
+//        client.stopJob(0);传入job id
+        client.printJobs();
+        client.showJobs();
+        client.importOnlineData("load data infile '/Users/4paradigm/IdeaProjects/OpenMLDB/java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/test.csv' " +
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java]: Simplify the test and do not add local path in the code base.

**Review by tobegit3hub — CHANGES_REQUESTED** [review]

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java (hunk 10 above)
Comment (yabg-shuai666) [reply java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: I get it

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java (hunk 13 above)
Comment (yabg-shuai666) [reply java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java]: I get it

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java (hunk 14 above)
Comment (yabg-shuai666) [reply java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java]: I get it

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java (hunk 9 above)
Comment (yabg-shuai666) [reply java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClient_Test.java]: I get it

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 15]
```diff
@@ -26,11 +26,13 @@
 import com.baidu.brpc.loadbalance.LoadBalanceStrategy;
 import com.baidu.brpc.protocol.Options;
 import java.util.ArrayList;
+import java.util.HashMap;
 import java.util.List;
 
 /***
  * Java wrapper for TaskManager brpc client.
  */
+
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Remove this empty line.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 16]
```diff
@@ -57,72 +61,272 @@ public TaskManagerClient(String endpoint) {
...
+        TaskManager.StopJobRequest request = TaskManager.StopJobRequest.newBuilder()
+                .setId(id)
+                .build();
+        TaskManager.StopJobResponse response = taskManagerInterface.StopJob(request);
+
+        if (response.getCode() != 0) {
+            String errorMessage = "Fail to request, code: " + response.getCode() + ", error: " + response.getMsg();
+            throw new Exception(errorMessage);
+        }
+        return response.getMsg();
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Do not return the message.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 17]
```diff
@@ -57,72 +61,272 @@ public TaskManagerClient(String endpoint) {
...
+    }
+    /**
+     * Run sql statements in batches.
+     *
+     * @param sql query sql string.
+     * @param output_path output path.
+     * @param default_db default database.
+     * @throws Exception
+     */
+    public void runBatchSql(String sql, String output_path, HashMap<String, String> conf, String default_db) throws Exception {
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Return the job id.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 18]
```diff
@@ -57,72 +61,272 @@ public TaskManagerClient(String endpoint) {
...
+                .setSql(sql)
+                .putAllConf(conf)
+                .setDefaultDb(default_db)
+                .build();
+        TaskManager.ShowJobResponse response = taskManagerInterface.RunBatchAndShow(request);
+        if (response.getCode() != 0) {
+            String errorMessage = "Fail to request, code: " + response.getCode() + ", error: " + response.getMsg();
+            throw new Exception(errorMessage);
+        }
+        return response.getMsg();
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Do not return the message and return the job id.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 19]
```diff
@@ -57,72 +61,272 @@ public TaskManagerClient(String endpoint) {
...
+                .setSql(sql)
+                .putAllConf(conf)
+                .setDefaultDb(default_db)
+                .build();
+        TaskManager.ShowJobResponse response = taskManagerInterface.ImportOnlineData(request);
+        if (response.getCode() != 0) {
+            String errorMessage = "Fail to request, code: " + response.getCode() + ", error: " + response.getMsg();
+            throw new Exception(errorMessage);
+        }
+        return response.getMsg();
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Do not return the message.

**Review by tobegit3hub — CHANGES_REQUESTED** [review]

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 20]
```diff
@@ -57,72 +60,282 @@ public TaskManagerClient(String endpoint) {
...
+        TaskManager.DropOfflineTableRequest request = TaskManager.DropOfflineTableRequest.newBuilder()
+                .setDb(db)
+                .setTable(table)
+                .build();
+        TaskManager.DropOfflineTableResponse response = taskManagerInterface.DropOfflineTable(request);
+        if (response.getCode() != 0) {
+            String errorMessage = "Fail to request, code: " + response.getCode() + ", error: " + response.getMsg();
+            throw new Exception(errorMessage);
+        }
+        return response.getMsg();
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: Do not return error message.

File: java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java [hunk 21]
```diff
@@ -57,72 +60,282 @@ public TaskManagerClient(String endpoint) {
...
+    /**
+     * Run sql statements in batches.
+     *
+     * @param sql query sql string.
+     * @param output_path output path.
+     * @param default_db default database.
+     * @return id of job.
+     * @throws Exception
+     */
+    public int runBatchSql(String sql, String output_path, HashMap<String, String> conf, String default_db) throws Exception {
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/main/java/com/_4paradigm/openmldb/taskmanager/client/TaskManagerClient.java]: The names of parameters would be `outputPath` instead `output_path`. We may change later.

File: java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java [hunk 22]
```diff
@@ -0,0 +1,24 @@
...
+import com._4paradigm.openmldb.taskmanager.client.TaskManagerClient;
+import org.testng.annotations.Ignore;
+import org.testng.annotations.Test;
+
+
+public abstract class TaskManagerClientTest {
+    @Ignore
+    @Test
+    public void TestManagerClient() throws Exception{
+        TaskManagerClient client = new TaskManagerClient("127.0.0.1:9995");
```
Comment (tobegit3hub) [inline java/openmldb-taskmanager/src/test/java/com/_4paradigm/openmldb/taskmanager/TaskManagerClientTest.java:12]: We may enable unit tests later since TaskManager has been started in onebox.

**Review by tobegit3hub — CHANGES_REQUESTED** [review]

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by dl239 — APPROVED** [review]
