### PR TITLE
fix: use int to record string length instead of map

### LINKED ISSUE #1979: Use int value to record string length instead of Map in `InsertPreparedStatementImpl `
Use int value to record string length instead of Map in [`InsertPreparedStatementImpl `](https://github.com/4paradigm/OpenMLDB/blob/main/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/sdk/impl/InsertPreparedStatementImpl.java#L55)

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Fixed #1979

* **What is the new behavior (if this is a feature change)?**
None

### CODE REVIEW

File: java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/SQLRouterSmokeTest.java [hunk 1]
```diff
@@ -367,9 +367,7 @@ public void testInsertPreparedState(SqlExecutor router) {
             insert = "insert into tsql1010 values(?, ?, ?, ?, ?);";
             PreparedStatement impl3 = router.getInsertPreparedStmt(dbname, insert);
             impl3.setLong(1, 1003);
-            impl3.setString(3, "zhejiangxx");
```
Comment (vagetablechicken) [inline java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/SQLRouterSmokeTest.java]: Mind that do not delete these lines

Comment (mangoGoForward) [reply java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/SQLRouterSmokeTest.java]: Got, I think use `List` or `Map` more better instead of `int`, because we want to implement multiple set and save the last value. So this issue and PR may unnecessary

Comment (mangoGoForward) [reply java/openmldb-jdbc/src/test/java/com/_4paradigm/openmldb/jdbc/SQLRouterSmokeTest.java]: Done, reverted

**Review by dl239 — APPROVED** [review]

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by aceforeverd — APPROVED** [review]
