### PR TITLE
fix: fix tablet core

### LINKED ISSUE #2830: Tablet coredump
version: 0.6.0
the tablet log as below:
```
W1122 15:14:52.672183 33843 tablet_impl.cc:1385] table is not exist. tid 82, pid 7
W1122 15:14:52.674259 33843 tablet_impl.cc:2140] table is not exist. tid 82, pid 2
W1122 15:14:52.712164 33844 tablet_catalog.cc:279] fail to get tablet: pk 2022112215143753985145 not exist
W1122 15:14:52.712221 33844 runner.cc:3769] fail to run proxy runner with rows: subquery tablet is null
W1122 15:14:52.712239 33844 runner.cc:3592] run proxy runner with rows fail, result table is null
```

if the `BatchRequestRun` return nullptr , tablet will core in https://github.com/4paradigm/OpenMLDB/blob/main/hybridse/src/vm/runner.cc#L1111

### PR DESCRIPTION
**Pull request by dl239**
fix core #2830

### CODE REVIEW

**Review by zhanghaohit — APPROVED** [review]

File: hybridse/src/vm/runner.cc [hunk 1]
```diff
@@ -1106,9 +1106,10 @@ std::shared_ptr<DataHandlerList> Runner::BatchRequestRun(RunnerContext& ctx) {
 
     for (size_t idx = 0; idx < ctx.GetRequestSize(); idx++) {
         inputs.clear();
-        for (size_t producer_idx = 0; producer_idx < producers_.size();
-             producer_idx++) {
-            inputs.push_back(batch_inputs[producer_idx]->Get(idx));
+        for (size_t producer_idx = 0; producer_idx < producers_.size(); producer_idx++) {
+            if (batch_inputs[producer_idx] != nullptr) {
+                inputs.push_back(batch_inputs[producer_idx]->Get(idx));
```
Comment (aceforeverd) [inline hybridse/src/vm/runner.cc]: batch request mode ?

File: hybridse/src/vm/runner.cc [hunk 2]
```diff
@@ -1106,9 +1106,10 @@ std::shared_ptr<DataHandlerList> Runner::BatchRequestRun(RunnerContext& ctx) {
...
+            }
```
Comment (aceforeverd) [inline hybridse/src/vm/runner.cc:1113]: input array size changed, not sure if problem arrise. or Construct a empty element instead of null ?

**Review by aceforeverd — APPROVED** [review]
