### PR TITLE
fix: pass sql file absolute path and fix for yarn-client mode

### LINKED ISSUE #2150: Fail to get sql file for yarn-client mode
Now we can parse sql file for local and yarn-cluster mode. But it fails for yarn-client mode.

### PR DESCRIPTION
**Pull request by tobegit3hub**
* Resolve https://github.com/4paradigm/OpenMLDB/issues/2150 .

### CODE REVIEW

File: java/openmldb-batchjob/src/main/scala/com/_4paradigm/openmldb/batchjob/util/OpenmldbJobUtil.scala [hunk 1]
```diff
@@ -31,13 +31,17 @@ object OpenmldbJobUtil {
...
-    val actualSqlFilePath = if (sparkMaster.equals("local")) {
-      SparkFiles.get(sqlFilePath)
+    val actualSqlFilePath = if (sparkMaster.equalsIgnoreCase("yarn") &&
+      sparkDeployMode.equalsIgnoreCase("cluster")) {
+      sqlFilePath.split("/").last
     } else {
       sqlFilePath
     }
 
+    println("tobe1: actualSqlFilePath: " + actualSqlFilePath)
```
Comment (tobegit3hub) [inline java/openmldb-batchjob/src/main/scala/com/_4paradigm/openmldb/batchjob/util/OpenmldbJobUtil.scala]: Remove the debug code.

**Review by dl239 — APPROVED** [review]

**Review by aceforeverd — APPROVED** [review]
