### PR TITLE
fix: fix compile warnings

### LINKED ISSUE #1785: Resolve compiling warnings
WX20220510-195326@2x

### PR DESCRIPTION
**Pull request by xuduling**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

File: src/storage/disk_table.cc [hunk 1]
```diff
@@ -984,7 +984,7 @@ DiskTableRowIterator::DiskTableRowIterator(rocksdb::DB* db, rocksdb::Iterator* i
                                            uint32_t ts_idx)
     : db_(db),
       it_(it),
-      snapshot_(snapshot),
+      const snapshot_(snapshot),
```
Comment (dl239) [inline src/storage/disk_table.cc]: why add `const` here

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by dl239 — APPROVED** [review]
