### PR TITLE
fix: print import rows count after finished

### LINKED ISSUE #1327: importer: count how many rows we read
https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java#L210-L221

We don't know how may rows we read. So count it and print a log.

You can use this logger https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java#L55
or `System.out.println` or any better ways for printing.

### PR DESCRIPTION
**Pull request by Manny-op**
* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

-fix that allows importer to know number of rows read. Resolve #1327

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

File: java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java [hunk 1]
```diff
@@ -209,16 +209,20 @@ public void Load() {
         reader.enableCheckHeader(tableMetaData);
         try {
             CSVRecord record;
+            int lines = 0;
             while ((record = reader.next()) != null) {
+                lines++;
+                // integer gets added at the start of iteration for each line.
```
Comment (vagetablechicken) [inline java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java]: It's better to comment above the code.

File: java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java [hunk 2]
```diff
@@ -209,16 +209,20 @@ public void Load() {
...
-
                 // distribute the row to the bulk load generators for each MemTable(tid, pid)
                 for (Integer pid : dims.keySet()) {
                     // Note: NS pid is int
                     // no need to calc dims twice, pass it to BulkLoadGenerator
                     generators.get(pid).feed(new BulkLoadGenerator.FeedItem(dims, tsIdxSet, record));
-                }
+                }    
             }
+            System.out.println(lines);
```
Comment (vagetablechicken) [inline java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java]: print "total read rows: " + lines

File: java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java [hunk 3]
```diff
@@ -209,16 +209,20 @@ public void Load() {
...
+                lines++;
                 Map<Integer, List<Tablet.Dimension>> dims = buildDimensions(record, keyIndexMap, tableMetaData.getPartitionNum());
-
                 // distribute the row to the bulk load generators for each MemTable(tid, pid)
                 for (Integer pid : dims.keySet()) {
                     // Note: NS pid is int
                     // no need to calc dims twice, pass it to BulkLoadGenerator
                     generators.get(pid).feed(new BulkLoadGenerator.FeedItem(dims, tsIdxSet, record));
-                }
+                }
```
Comment (aceforeverd) [inline java/openmldb-import/src/main/java/com/_4paradigm/openmldb/importer/Importer.java]: no trailing whitespace

**Review by lumianph — APPROVED** [review]

**Review by vagetablechicken — APPROVED** [review]
