### PR TITLE
fix: convert all non-const ref job_info to pointer in sql_cluster_router.h

### LINKED ISSUE #2135: cpplint: convert all non-const ref `job_info` to pointer in sql_cluster_router.h
https://github.com/4paradigm/OpenMLDB/blob/c748d5887a0409433f0d68b43fc8792bcde69d89/src/sdk/sql_cluster_router.h#L266

We use `JobInfo& job_info` to be the output, it's not good. We should convert it to a pointer.
Contains:
`ImportOnlineData`, `ImportOfflineData`, `ExportOfflineData`, `ExecuteOfflineQueryAsync`, `ExecuteOfflineQueryGetOutput`

### PR DESCRIPTION
**Pull request by jiang1997**
Closes #2135

### CODE REVIEW

**Review by dl239 — DISMISSED** [review]

File: src/sdk/sql_cluster_test.cc [hunk 1]
```diff
@@ -411,7 +411,7 @@ TEST_F(SQLSDKQueryTest, GetTabletClient) {
         ASSERT_TRUE(request_row->Build());
         auto sql_cluster_router = std::dynamic_pointer_cast<SQLClusterRouter>(router);
         hybridse::sdk::Status sdk_status;
-        auto client = sql_cluster_router->GetTabletClient(db, sql, hybridse::vm::kRequestMode, request_row, sdk_status);
+        auto client = sql_cluster_router->GetTabletClient(db, sql, hybridse::vm::kRequestMode, request_row, &sdk_status);
```
Comment (dl239) [inline src/sdk/sql_cluster_test.cc]: please resolve the `cpplint` error. 
`src/sdk/sql_cluster_test.cc:414:  Lines should be <= 120 characters long  [whitespace/line_length`

**Review by vagetablechicken — APPROVED** [review]

**Review by dl239 — APPROVED** [review]
