### PR TITLE
fix: type problem of index in get_parameter_row() and get_request_row…

### LINKED ISSUE #2673: Resolve comparison of integer expressions warning in src/sdk/openmldb_api.cc
```
/openmldb/src/sdk/openmldb_api.cc: In member function ‘std::shared_ptr<openmldb::sdk::SQLRequestRow> ParameterRow::get_parameter_row() const’:
/openmldb/src/sdk/openmldb_api.cc:60:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::any>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
     for (int i = 0; i < record_.size(); ++i) {
                     ~~^~~~~~~~~~~~~~~~
/openmldb/src/sdk/openmldb_api.cc: In member function ‘std::shared_ptr<openmldb::sdk::SQLRequestRow> RequestRow::get_request_row() const’:
/openmldb/src/sdk/openmldb_api.cc:187:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::any>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
     for (int i = 0; i < record_.size(); ++i) {
```

### PR DESCRIPTION
**Pull request by Jake-00**
…(), within file /openmldb/src/sdk/openmldb_api.cc

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
When calling method get_parameter_row() or get_request_row(), it would raise a warning "warning: comparison of integer expressions of different signedness". Referring to the warning information, I found that the exact problem was not proper type assignment of for-loop index. Indeed it should be unsigned long but for int, and I modified for-loop index type from int to unsigned long both in get_parameter_row() and get_request_row().

* **What is the current behavior?** (You can also link to an open issue here)
Resolve comparison of integer expressions warning in src/sdk/openmldb_api.cc https://github.com/4paradigm/OpenMLDB/issues/2673

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

**Comment by Jake-00** [comment]
Hi, there. I am confused that the reason of 0% patch coverage in Codecov Report. Dose it affect quality of this pr?

File: src/sdk/openmldb_api.cc [hunk 1]
```diff
@@ -57,7 +57,7 @@ ParameterRow::ParameterRow(const OpenmldbHandler* handler) : handler_(handler) {
 std::shared_ptr<openmldb::sdk::SQLRequestRow> ParameterRow::get_parameter_row() const {
     sql_parameter_row_ = ::openmldb::sdk::SQLRequestRow::CreateSQLRequestRowFromColumnTypes(parameter_types_);
     sql_parameter_row_->Init(str_length_);
-    for (int i = 0; i < record_.size(); ++i) {
+    for (unsigned long int i = 0; i < record_.size(); ++i) {
```
Comment (dl239) [inline src/sdk/openmldb_api.cc]: please resolve cpplint warning

**Comment by dl239** [comment]
> Hi, there. I am confused that the reason of 0% patch coverage in Codecov Report. Dose it affect quality of this pr?

you can ignore the coverage  report in this pr.

File: src/sdk/openmldb_api.cc (hunk 1 above)
Comment (Jake-00) [reply src/sdk/openmldb_api.cc]: Thanks for your helpful response, I have converted the for-loop counter's type from `unsigned long int` to `size_t`, in which caused cpplint warnings.

**Review by dl239 — APPROVED** [review]

**Review by aceforeverd — APPROVED** [review]
