### PR TITLE
fix: refactor taskmanager config and support deleting HDFS files when dropping tables

### LINKED ISSUE #1266: Delete hdfs file without setting namenode.uri for TaskManager
Now we have to set `namenode.uri` to delete hdfs file.

### LINKED ISSUE #2787: Remove the config of `namenode.uri` in TaskManager
We may support reading HDFS without setting `namenode.uri`.

### PR DESCRIPTION
**Pull request by tobegit3hub**
* Refactor and print final taskmanager configs
* Resolve https://github.com/4paradigm/OpenMLDB/issues/2787
* Resolve https://github.com/4paradigm/OpenMLDB/issues/1266

Breaking change: Remove the deprecated TaskManager config of "namenode.uri".

### CODE REVIEW

**Review by vagetablechicken — APPROVED** [review]

**Review by dl239 — APPROVED** [review]

**Review by lqy222 — APPROVED** [review]

File: release/sbin/deploy-all.sh [hunk 1]
```diff
@@ -132,7 +132,7 @@ function download_spark {
       if [[ -e "${spark_tar}" ]]; then
         echo "Skip downloading openmldbspark as ${spark_tar} already exists"
       else
-        url="https://github.com/4paradigm/spark/releases/download/v3.2.1-openmldb${OPENMLDB_VERSION}/${spark_tar}"
+        url="https://github.com/4paradigm/spark/releases/download/v3.2.1-openmldb0.7.1/${spark_tar}"
```
Comment (dl239) [inline release/sbin/deploy-all.sh]: why use the fixed version?

Comment (tobegit3hub) [reply release/sbin/deploy-all.sh]: It is for testing and has been reverted.
