### PR TITLE
fix: run `start.sh` failed if has not installed `curl`

### LINKED ISSUE #2624: run `start.sh` failed if has not installed `curl`
WX20221009-110044

### PR DESCRIPTION
**Pull request by dl239**
- run `start.sh` failed if has not installed `curl`
- update `sh` to `bash` in documents

### CODE REVIEW

File: release/bin/start.sh [hunk 1]
```diff
@@ -75,21 +75,30 @@ case $OP in
...
+                    elif kill -0 "$PID" > /dev/null 2>&1; then
+                        echo $PID > "$OPENMLDB_PID_FILE"
+                        echo "Start ${COMPONENT} success"
+                        exit 0
+                    else
+                        break
+                    fi
+                done
+            else
+                sleep 2
```
Comment (vagetablechicken) [inline release/bin/start.sh]: plz add some echo comments, e.g. "no curl, sleep 2 then check the process running status", in curl branch, " max wait time is 12s"

Comment (dl239) [reply release/bin/start.sh]: no curl message has added.  i think the max wait time is not necessary in startup script.

File: release/bin/start.sh [hunk 2]
```diff
@@ -72,24 +72,34 @@ case $OP in
         fi
 
         if [ "$COMPONENT" != "taskmanager" ]; then
-            ./bin/openmldb --flagfile=./conf/"$COMPONENT".flags --enable_status_service=true >>  "$LOG_DIR"."$COMPONENT".log 2>&1 &
+            ./bin/openmldb --flagfile=./conf/"$COMPONENT".flags --enable_status_service=true >> "$LOG_DIR"."$COMPONENT".log 2>&1 &
```
Comment (vagetablechicken) [inline release/bin/start.sh]: If openmldb is incompatible, e.g. released bin runs on ubuntu22, will the error msg write to this log file?
If start failed, we'd better to print hint, like 'check log in "$LOG_DIR"."$COMPONENT".log and $LOG_DIR"/"$COMPONENT".INFO'

**Review by vagetablechicken — APPROVED** [review]

**Review by aceforeverd — APPROVED** [review]
