### PR TITLE
fix: fix same schema name bug

### LINKED ISSUE #484: Bug: Failed to merge incompatible data types string and int
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

### SQL Case
```yaml
  - id: 0
    desc: window query after last join with a table, index hasn't been optimized
    db: db1
    mode: rtidb-unsupport
    tags: ["TODO", "@tobe @zekai",
        "Failed to merge fields 'col0' and 'col0'. Failed to merge incompatible data types string and int"]
    sql: |
       SELECT sum(t1.col1) over w1 as sum_t1_col1, str1 as t2_str1
       FROM t1
       last join t2 order by t2.col1
       on t1.col1 = t2.col1 and t1.col2 = t2.col0
       WINDOW w1 AS (
        PARTITION BY t1.col2 ORDER BY t1.col1
        ROWS_RANGE BETWEEN 3 PRECEDING AND CURRENT ROW
       ) limit 10;
    inputs:
      - name: t1
        columns: ["col0 string", "col1 bigint", "col2 int"]
        indexs: ["index1:col0:col1"]
        rows:
          - ["0", 1, 5]
          - ["0", 2, 5]
      - name: t2
        columns: ["str0 string", "str1 string", "col0 int", "col1 bigint"]
        indexs: ["index2:str0:col1"]
        rows:
          - ["2", "EEEEE", 55, 5]
          - ["1", "DDDD", 55, 4]
          - ["1", "CCC", 55, 3]
    expect:
      success: true 
```
## Expected Behavior

Compile and run success in OpenMLDB-batch
## Current Behavior
```
Failed to merge fields 'col0' and 'col0'. Failed to merge incompatible data types string and int
```

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by zekai427**
- Issue：https://github.com/4paradigm/OpenMLDB/issues/484
- In batch 'joinPlan', when columns schema use same name, spark have a bug. This is spark issue: https://issues.apache.org/jira/browse/SPARK-36932.
- To avoid triggering this spark bug in joinPlan, we use mapPartition instead of groupByKey.

### CODE REVIEW

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala [hunk 1]
```diff
@@ -20,18 +20,97 @@ import com._4paradigm.hybridse.sdk.HybridSeException
...
+
+    // Add the row in last partition
+    if (maxRow != null) {
+      resultRows += maxRow
+    }
+
+    resultRows
+  }
+
+  def minRows(iterator: Iterator[Row], groupByColIndex: Int, orderByColIndex: Int, orderByColType: DataType)
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala]: Merge into the method `maxRows` to reuse the similar logic.

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala [hunk 2]
```diff
@@ -20,18 +20,97 @@ import com._4paradigm.hybridse.sdk.HybridSeException
...
+
+    var maxValue: Long = Long.MinValue
+    var maxRow: Row = null
+    var first = true
+
+    while (iterator.hasNext) {
+      val row = iterator.next()
+      val currentPartitionKey = row.getLong(groupByColIndex)
+      // Determine whether it is in the same partition
+      if (lastRowPartitionKey != Long.MinValue && currentPartitionKey != lastRowPartitionKey) {
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala]: What if the value of partition key is `Long.MinValue`, it may be treated as the new partition.

**Review by tobegit3hub — CHANGES_REQUESTED** [review]

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala [hunk 3]
```diff
@@ -20,18 +20,81 @@ import com._4paradigm.hybridse.sdk.HybridSeException
...
+    var resultRow: Row = null
+    var first = true
+
+    while (iterator.hasNext) {
+      val row = iterator.next()
+      val currentPartitionKey = row.getLong(groupByColIndex)
+      // Determine whether it is in the same partition
+      if (currentPartitionKey != lastRowPartitionKey) {
+        // Add the max(or min) row
+        resultRows += resultRow
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala]: This will add the null element in ArrayBuffer when handling the first item of iterator.

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala [hunk 4]
```diff
@@ -20,18 +20,81 @@ import com._4paradigm.hybridse.sdk.HybridSeException
...
+      if (x < y) {
+        true
+      } else {
+        false
+      }
+    }
+  }
+
+  // Get max(or min) rows in each partition
+  def getRows(iterator: Iterator[Row], groupByColIndex: Int,
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala]: It would be better to `getMinOrMaxRows`

**Comment by tobegit3hub** [comment]
We may refactor by using rdd functions like this.

```
val distinctRdd = df.rdd.map({ row =>
      (row.getInt(0), row)
    }).reduceByKey({ (row1, row2) =>
      if (row1.getLong(1) > row2.getLong(1)) row1 else row2
    }).values

val distinctDf = spark.createDataFrame(distinctRdd, df.schema)
```

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala [hunk 5]
```diff
@@ -119,76 +118,67 @@ object JoinPlan {
...
-                iter.maxBy(row => {
-                  if (row.isNullAt(timeIdxInJoined)) {
-                    Long.MinValue
-                  } else {
-                    timeExtractor.apply(row)
-                  }
-                })
+        val indexCol = SparkColumnUtil.getColumnFromIndex(joined, indexColIdx)
+
+        val distinctRdd = joined.repartition(indexCol).rdd.map({
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala]: It seems that `repartition` is not required for this function.

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala [hunk 6]
```diff
@@ -119,76 +118,67 @@ object JoinPlan {
...
+          row => (row.getLong(indexColIdx), row)
+        }).reduceByKey({
+          (row1, row2) =>
+            val dataType = joined.schema.fields(timeIdxInJoined).dataType
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala]: This variable could be rename to `timeColDataType` or `timeColType`.

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala [hunk 7]
```diff
@@ -119,76 +118,67 @@ object JoinPlan {
...
+            val data1 = SparkRowUtil.getLongFromIndex(timeIdxInJoined, dataType, row1)
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala]: This variable could be rename to `rowTimeValue1`.

File: java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala [hunk 8]
```diff
@@ -119,76 +118,67 @@ object JoinPlan {
...
+            val data2 = SparkRowUtil.getLongFromIndex(timeIdxInJoined, dataType, row2)
+            if (isAsc) {
+              if (data1 > data2) {
```
Comment (tobegit3hub) [inline java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala]: In scala, single line for simple if-else is more readable. Could be changed to this.

`if (rowTimeValue1 > rowTimeValue2) row1 else row2`.

**Review by tobegit3hub — CHANGES_REQUESTED** [review]

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by dl239 — APPROVED** [review]
