### PR TITLE
fix: memroy leak in zk_client.cc

### LINKED ISSUE #1659: Memory leak in zk_client.cc
**Bug Description**
`zoo_get_children` will allocate memory in `struct String_vector`, we need to use `deallocate_String_vector` to free memory by ourself.

https://github.com/4paradigm/OpenMLDB/blob/4403222f75820d971bf00ed7c0af4c73391eb6b1/src/zk/zk_client.cc#L498
https://github.com/4paradigm/OpenMLDB/blob/4403222f75820d971bf00ed7c0af4c73391eb6b1/src/zk/zk_client.cc#L523

There are two place to call `zoo_get_children`, I think we can add `deallocate_String_vector(&data)` at line 505 and line 530 to fix this bug.

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

### PR DESCRIPTION
**Pull request by wuxiaobai24**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix memory leak in zk_client.cc.

* **What is the current behavior?** (You can also link to an open issue here)
It should resolve #1659

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

File: src/zk/zk_client.cc [hunk 1]
```diff
@@ -503,6 +503,7 @@ bool ZkClient::GetChildrenUnLocked(const std::string& path, std::vector<std::str
     for (int32_t i = 0; i < data.count; i++) {
         children.push_back(std::string(data.data[i]));
     }
+    deallocate_String_vector(&data);
```
Comment (aceforeverd) [inline src/zk/zk_client.cc]: how about free in RAII way, in case program accidentally return before e.g in line 504. 
Use `abs::Cleanup`: https://github.com/abseil/abseil-cpp/blob/master/absl/cleanup/cleanup.h#L81

Comment (wuxiaobai24) [reply src/zk/zk_client.cc]: ok

**Review by aceforeverd — APPROVED** [review]

**Comment by aceforeverd** [comment]
thank you！
