### PR TITLE
fix: sql client set ttl when creating index 

### LINKED ISSUE #156: 创建索引后，desc不展示ttl的值
## Expected Behavior
期望结果，在desc时展示ttl的值

## Current Behavior
wecom-temp-4158b1c407045be244b401799de6f484

## Steps to Reproduce
1.先创建一个带索引的表
2.在单独创建索引
3.desc

### PR DESCRIPTION
**Pull request by vagetablechicken**
Closes #156 

add a static method `TTLTypeParse` for parsing string to ttl type.

### CODE REVIEW

File: src/cmd/sql_cmd.h [hunk 1]
```diff
@@ -509,6 +508,14 @@ void HandleCreateIndex(const hybridse::node::CreateIndexNode *create_index_node)
...
     }
     column_key.set_ts_name(create_index_node->index_->GetTs());
+    auto setTTL = column_key.mutable_ttl();
+    ::openmldb::type::TTLType ttl_type;
+    if (!::openmldb::client::NsClient::TTLTypeParse(create_index_node->index_->ttl_type(), &ttl_type)) {
+        std::cout << "ttl type " << create_index_node->index_->ttl_type() << " is invalid" << std::endl;
+        return;
+    }
+    setTTL->set_ttl_type(ttl_type);
+    setTTL->set_abs_ttl(create_index_node->index_->GetAbsTTL());
```
Comment (dl239) [inline src/cmd/sql_cmd.h]: set lat_ttl

File: src/cmd/sql_cmd.h [hunk 2]
```diff
@@ -509,6 +508,14 @@ void HandleCreateIndex(const hybridse::node::CreateIndexNode *create_index_node)
         column_key.add_col_name(key);
     }
     column_key.set_ts_name(create_index_node->index_->GetTs());
+    auto setTTL = column_key.mutable_ttl();
```
Comment (dl239) [inline src/cmd/sql_cmd.h]: var name use [google style](https://google.github.io/styleguide/cppguide.html#Variable_Names)

**Review by dl239 — APPROVED** [review]

**Review by imotai — APPROVED** [review]
