### PR TITLE
fix: sql and ns client desc result

### LINKED ISSUE #331: bug: sql client `desc` result
Ns client `showschema` use `PrintColumnKey` to show indexes.
Currently, sql client `desc` can't show multi keys and ttl is not 'xx min'.
Sql client could use `PrintColumnKey` to reach an agreement.

### PR DESCRIPTION
**Pull request by vagetablechicken**
Closes #331 
Sql client & ns client use the same print functions.

### CODE REVIEW

File: src/cmd/display.h [hunk 1]
```diff
@@ -25,6 +25,7 @@
 #include <utility>
 #include <vector>
 
+#include "base/texttable.h"
```
Comment (dl239) [inline src/cmd/display.h:28]: base/texttable.h is not exist

**Review by dl239 — APPROVED** [review]

**Review by zekai427 — APPROVED** [review]
LGTM
