### PR TITLE
fix: check negative ts

### LINKED ISSUE #2686: Return failed if the value of `ts` column is negative
- `Put`/`BulkLoad`  in storage/mem_table.cc and storage/disk_table.cc
- sdk/sql_insert_row.cc

### PR DESCRIPTION
**Pull request by dl239**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

**Review by vagetablechicken — APPROVED** [review]

File: src/storage/aggregator_test.cc [hunk 1]
```diff
@@ -84,18 +84,18 @@ bool UpdateAggr(std::shared_ptr<Aggregator> aggr, codec::RowBuilder* row_builder
...
-        row_builder->AppendInt32(i);
-        row_builder->AppendInt16(i);
-        row_builder->AppendInt64(i);
-        row_builder->AppendFloat(static_cast<float>(i));
-        row_builder->AppendDouble(static_cast<double>(i));
-        row_builder->AppendDate(i);
-        row_builder->AppendString(str.c_str(), str.size());
-        row_builder->AppendNULL();
-        row_builder->AppendInt32(i % 2);
+        (void)row_builder->AppendString("id1", 3);
```
Comment (aceforeverd) [inline src/storage/aggregator_test.cc:87]: good first issue for those ?

**Review by aceforeverd — APPROVED** [review]

File: src/storage/aggregator_test.cc (hunk 1 above)
Comment (dl239) [reply src/storage/aggregator_test.cc:87]: all warnings about these function have been fixed

**Review by lqy222 — APPROVED** [review]
