### PR TITLE
fix: python test and cicd

### LINKED ISSUE #270: CICD: python sdk test
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

https://github.com/4paradigm/OpenMLDB/runs/3353568786?check_suite_focus=true
## Expected Behavior

It will be more reasonable to notify a fail when a python sdk test error.

## Current Behavior
https://github.com/4paradigm/OpenMLDB/pull/248/checks?check_run_id=3354075265
image

## Steps to Reproduce

1.
2.
3.
4.

### LINKED ISSUE #354: bug: cicd python test
sqlalchemy-test/ is not existed, #246 moved test file, but fesql_test_python.sh doesn't be fixed.

### PR DESCRIPTION
**Pull request by vagetablechicken**
Closes #270, #354 

Fix python ut and test script for cicd, we can get error if cicd python test is failed now.

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

File: steps/fesql_test_python.sh [hunk 1]
```diff
@@ -34,9 +34,9 @@ whl_name=$(ls openmldb*.whl)
 echo "whl_name:${whl_name}"
 python3 -m pip install "${whl_name}" -i https://pypi.tuna.tsinghua.edu.cn/simple
 
-# needs: easy_install nose sqlalchemy
-cd "${ROOT_DIR}"/python/sqlalchemy-test
-nosetests --with-xunit
+# needs: easy_install nose (sqlalchemy is openmldb required)
+cd "${ROOT_DIR}"/python/test || exit
```
Comment (aceforeverd) [inline steps/fesql_test_python.sh]: set -x can emit 'exit'

Comment (vagetablechicken) [reply steps/fesql_test_python.sh]: do you mean '-e'? '-x' only print cmd.

File: steps/fesql_test_python.sh [hunk 2]
```diff
@@ -14,29 +14,31 @@
...
-# needs: easy_install nose sqlalchemy
-cd "${ROOT_DIR}"/python/sqlalchemy-test
+# needs: easy_install nose (sqlalchemy is openmldb required)
+cd "${ROOT_DIR}"/python/test
 nosetests --with-xunit
 
-cd "${ROOT_DIR}"/onebox && sh stop_all.sh && cd "$ROOT_DIR" || exit
-cd thirdsrc/zookeeper-3.4.14 || ./bin/zkServer.sh stop && cd "$ROOT_DIR" || exit
+cd "${ROOT_DIR}"/onebox && sh stop_all.sh && cd "$ROOT_DIR"
+cd thirdsrc/zookeeper-3.4.14 || ./bin/zkServer.sh stop && cd "$ROOT_DIR"
```
Comment (aceforeverd) [inline steps/fesql_test_python.sh]: `||` ?

**Review by aceforeverd — APPROVED** [review]
