### PR TITLE
fix(#1410): log error and return at the end of switch statement in `ShadowCopy` function

### LINKED ISSUE #1410: Add `return` after the `switch` statement
WX20220310-093747

It needs to add `return` after the `switch` statement in `ShadowCopy` function. Please log error message such as 'Unsupported Data type' and return nullptr;

### PR DESCRIPTION
**Pull request by TheFu527**
* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

https://github.com/4paradigm/OpenMLDB/issues/1410

* **What is the new behavior (if this is a feature change)?**

Add default to the switch statement in ShadowCopy function. Log error message 'Unsupported Data type' and return nullptr.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No.

* **Other information**:

### CODE REVIEW

File: hybridse/src/node/expr_node.cc [hunk 1]
```diff
@@ -918,6 +918,10 @@ ConstNode* ConstNode::ShadowCopy(NodeManager* nm) const {
             LOG(WARNING) << "Fail to copy primary expr of type " << node::DataTypeName(GetDataType());
             return nm->MakeConstNode(GetDataType());
         }
+        
+        default:
+            LOG(ERROR) << "Unsupported Data type";
```
Comment (dl239) [inline hybridse/src/node/expr_node.cc]: Append the current data type to log info
`LOG(ERROR) << "Unsupported Data type " << node::DataTypeName(GetDataType())`

File: hybridse/src/node/expr_node.cc [hunk 2]
```diff
@@ -918,6 +918,10 @@ ConstNode* ConstNode::ShadowCopy(NodeManager* nm) const {
             LOG(WARNING) << "Fail to copy primary expr of type " << node::DataTypeName(GetDataType());
             return nm->MakeConstNode(GetDataType());
         }
+
```
Comment (dl239) [inline hybridse/src/node/expr_node.cc]: please resolve the cpplint warning

File: hybridse/src/node/expr_node.cc [hunk 3]
```diff
@@ -918,6 +918,10 @@ ConstNode* ConstNode::ShadowCopy(NodeManager* nm) const {
...
+        default:
```
Comment (aceforeverd) [inline hybridse/src/node/expr_node.cc]: `default` prevent static analyzer generate error if any new Datatype added. Instead, put those simply after switch block

Comment (TheFu527) [reply hybridse/src/node/expr_node.cc]: So nothing should be done in the default case?

Comment (dl239) [reply hybridse/src/node/expr_node.cc]: hi @TheFu527 ,  the advices of @aceforeverd is to remove the `default` statement and add logging and return at the end of switch block as follows:
switch: {
     case xxx
}
LOG xxxx;
return nullptr;

File: hybridse/src/node/expr_node.cc [hunk 4]
```diff
@@ -918,7 +918,12 @@ ConstNode* ConstNode::ShadowCopy(NodeManager* nm) const {
             LOG(WARNING) << "Fail to copy primary expr of type " << node::DataTypeName(GetDataType());
             return nm->MakeConstNode(GetDataType());
         }
+
+        default: {
```
Comment (aceforeverd) [inline hybridse/src/node/expr_node.cc]: just rm default, line 925-926 is enough

**Review by dl239 — APPROVED** [review]

**Review by aceforeverd — APPROVED** [review]
