### PR TITLE
fix: clear-all

### LINKED ISSUE #3210: `clear-all.sh` script has not clear the hdd/ssd data directory
`clear-all.sh` script has not clear the hdd/ssd data directory. refer https://github.com/4paradigm/OpenMLDB/blob/v0.7.3/release/sbin/clear-all.sh#L37

### PR DESCRIPTION
**Pull request by dl239**
close #3210

### CODE REVIEW

File: release/sbin/clear-all.sh [hunk 1]
```diff
@@ -35,6 +35,19 @@ rm_dir() {
...
+  conf_file="conf/tablet.flags.template"
+  dirname=""
+  while IFS= read -r line
+  do
+    if echo "$line" | grep -q '^#'; then
+      continue
+    fi
+    if echo "$line" | grep -v "zk_root_path" | grep -q "root_path" ||
+        echo "$line" |  grep -q "openmldb_log_dir"; then
+      cur_dirname=$(echo "${line}" | awk -F '=' '{print $2}')
```
Comment (aceforeverd) [inline release/sbin/clear-all.sh]: kind unsafe
```sh
echo 'root_path=/ abc' | awk -F '=' '{print $2}'
```

is `/` and `abc`, it will erase the whole system

Comment (aceforeverd) [reply release/sbin/clear-all.sh]: If possible, it should never runs under root

File: release/sbin/clear-all.sh [hunk 2]
```diff
@@ -35,6 +35,26 @@ rm_dir() {
...
+      dirname="${dirname} ${cur_dirname}"
+    fi
+  done < "$conf_file"
+  for item in $dirname
```
Comment (aceforeverd) [inline release/sbin/clear-all.sh]: Don't do the dirty check. A common fix to that problem is double quoting the path, so `rm / abc` become `rm "/ abc"`. 
You can declare `dirname` as array, or manually concat with double quotes.

File: release/sbin/clear-all.sh [hunk 3]
```diff
@@ -35,6 +35,18 @@ rm_dir() {
...
+  conf_file="conf/tablet.flags.template"
+  dirname=()
+  while IFS= read -r line
+  do
+    if echo "$line" | grep -q '^#'; then
+      continue
+    fi
+    if echo "$line" | grep -v "zk_root_path" | grep -q "root_path" ||
+        echo "$line" |  grep -q "openmldb_log_dir"; then
+      dirname[${#dirname[*]}]=$(echo "${line}" | awk -F '=' '{print $2}')
```
Comment (aceforeverd) [inline release/sbin/clear-all.sh]: dirname+=

File: release/sbin/clear-all.sh [hunk 4]
```diff
@@ -48,8 +60,15 @@ else
       rm_dir "$host" "$dir"
     else
       echo "clear tablet data and log in $dir with endpoint $host:$port "
-      cmd="cd $dir && rm -rf recycle db logs"
-      run_auto "$host" "$cmd"
+      for item in "${dirname[@]}"
+      do
+        if [[ $item == "/" ]]; then
```
Comment (aceforeverd) [inline release/sbin/clear-all.sh]: there are many cases elsewhere like `/usr`, we can't hard check it. 

If the array `dirname` is constructed corrected, simply make the cmd as
```bash
cmd="cd $dir && rm -rf \"$item\""
```

**Review by aceforeverd — CHANGES_REQUESTED** [review]

File: release/sbin/clear-all.sh (hunk 3 above)
Comment (dl239) [reply release/sbin/clear-all.sh]: what dose it mean?

**Review by tobegit3hub — APPROVED** [review]
LGTM

File: release/sbin/clear-all.sh (hunk 3 above)
Comment (aceforeverd) [reply release/sbin/clear-all.sh]: array concat: https://stackoverflow.com/a/1951523

File: release/sbin/clear-all.sh (hunk 4 above)
Comment (dl239) [reply release/sbin/clear-all.sh]: `/` is protected by `preserve-root` option default.

**Review by aceforeverd — APPROVED** [review]
