### PR TITLE
fix: fix memory leak in tablet_impl_test

### LINKED ISSUE #2579: Fix memory leak in tablet_impl_test
https://github.com/4paradigm/OpenMLDB/blob/v0.6.2/src/tablet/tablet_impl_test.cc#L3576
https://github.com/4paradigm/OpenMLDB/blob/v0.6.2/src/tablet/tablet_impl_test.cc#L3624

fix as below:
```
::openmldb::api::TraverseResponse srp;
tablet.Traverse(NULL, &sr, &srp, &closure);
ASSERT_EQ(0, srp.code());
ASSERT_EQ(100, (signed)srp.count());
```

### PR DESCRIPTION
**Pull request by haseeb-xd**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Modified code in tablet_impl_test.cc

* **What is the current behavior?** (You can also link to an open issue here)

Issue #2579

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

File: src/tablet/tablet_impl_test.cc [hunk 1]
```diff
@@ -3573,10 +3573,10 @@ TEST_P(TabletImplTest, AbsAndLat) {
...
         sr.set_limit(100);
         sr.set_idx_name("index1");
-        ::openmldb::api::TraverseResponse* srp = new ::openmldb::api::TraverseResponse();
-        tablet.Traverse(NULL, &sr, srp, &closure);
-        ASSERT_EQ(0, srp->code());
-        ASSERT_EQ(80, (signed)srp->count());
+        ::openmldb::api::TraverseResponse srp;
+        tablet.Traverse(NULL, &sr, &srp, &closure);
+        ASSERT_EQ(0, srp.code());
+        ASSERT_EQ(100, (signed)srp.count());
```
Comment (dl239) [inline src/tablet/tablet_impl_test.cc:3579]: hi @haseeb-xd , please revert the value of ASSERT

**Review by dl239 — APPROVED** [review]

**Review by vagetablechicken — APPROVED** [review]
