### PR TITLE
fix: pre-aggr table indexing schema

### LINKED ISSUE #2307: filter_key is not added into the dimension key
**Bug Description**
The index of pre-aggr table is <key, filter_key>. However, in `aggregator`, the dimension key is `key` only, which is not consistent with the index definition.

Two possible solutions:
- add the `filter_key` to the dimension key (problem: cannot easily delete if base table deletes)
- change the index to <key> (problem: there will be multiple entries for the  same <key, ts>. It is not feasible for disk table).

### PR DESCRIPTION
**Pull request by zhanghaohit**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- the pre-aggr table index definition is not consistent with the table access
   Close #2307
- aligned start_ts for range pre-aggr batch

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

File: src/storage/aggregator.cc [hunk 1]
```diff
@@ -157,10 +159,10 @@ bool Aggregator::Update(const std::string& key, const std::string& row, const ui
         int64_t latest_ts = aggr_buffer.ts_end_ + 1;
```
Comment (aceforeverd) [inline src/storage/aggregator.cc]: unused variable

**Comment by aceforeverd** [comment]
one test failed `TabletImplTest.AggregatorRecovery`

**Comment by zhanghaohit** [comment]
> one test failed `TabletImplTest.AggregatorRecovery`

fixed

**Review by aceforeverd — APPROVED** [review]
