### PR TITLE
fix:  join brpc server after stop it

### LINKED ISSUE #2157: bug: we should join after stop brpc server
https://github.com/4paradigm/OpenMLDB/blob/012db063a7f69b55733d3d39db7ed326ad1c2af6/src/sdk/mini_cluster.h#L140-L145

plz join every brpc server after stop it.

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
 join brpc server after stop it
 fix #2157 

* **What is the new behavior (if this is a feature change)?**
None

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

File: src/sdk/mini_cluster.h [hunk 1]
```diff
@@ -277,6 +278,7 @@ class StandaloneEnv {
     void Close() {
         ns_.Stop(10);
         tb_server_.Stop(10);
```
Comment (vagetablechicken) [inline src/sdk/mini_cluster.h:281]: ns_ needs join too

Comment (mangoGoForward) [reply src/sdk/mini_cluster.h:281]: Done.

**Review by vagetablechicken — APPROVED** [review]
