### PR TITLE
fix: fix nameserver fatal coredump

### LINKED ISSUE #3432: nameserver will coredump if create system table failed
nameserver will log fatal message if create system failed. glog will call `abort` after log message
https://github.com/google/glog/blob/v0.4.0/src/logging.cc#L1522-L1529

### PR DESCRIPTION
**Pull request by dl239**
close #3432

### CODE REVIEW

File: src/nameserver/name_server_impl.cc [hunk 1]
```diff
@@ -9596,15 +9596,15 @@ std::shared_ptr<TabletInfo> NameServerImpl::GetTablet(const std::string& endpoin
 void NameServerImpl::CreateDatabaseOrExit(const std::string& db) {
     auto status = CreateDatabase(db, true);
     if (!status.OK() && status.code != ::openmldb::base::ReturnCode::kDatabaseAlreadyExists) {
-        LOG(FATAL) << "create database failed. code=" << status.GetCode() << ", msg=" << status.GetMsg();
+        LOG(ERROR) << "create database failed. code=" << status.GetCode() << ", msg=" << status.GetMsg();
```
Comment (aceforeverd) [inline src/nameserver/name_server_impl.cc:9599]: WHAT's the difference ? you still calls exit afterwards

Comment (dl239) [reply src/nameserver/name_server_impl.cc:9599]: #3432

**Review by aceforeverd — APPROVED** [review]

**Review by vagetablechicken — APPROVED** [review]
