### PR TITLE
fix: send snapshot for disk table

### LINKED ISSUE #2026: SSD table addreplica is failure
**Bug Description**
企业微信截图_f6e68606-ac4f-43b8-b7ff-c5811129f5bf

企业微信截图_89024caa-2020-429c-aadf-4c36806c1547

**Expected Behavior**
SSD table addreplica is success.

**Steps to Reproduce**

1. 
2. 
3. 
4.

### PR DESCRIPTION
**Pull request by zhanghaohit**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix #2026

* **What is the current behavior?** (You can also link to an open issue here)
Currently the `storage_mode` is not passed when sending snapshot. Thus the follower tablet copies the data into the wrong directory.

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

File: src/replica/snapshot_replica_test.cc [hunk 1]
```diff
@@ -206,7 +216,118 @@ TEST_F(SnapshotReplicaTest, LeaderAndFollower) {
     sleep(2);
 }
 
-TEST_F(SnapshotReplicaTest, LeaderAndFollowerTS) {
+TEST_P(SnapshotReplicaTest, SendSnapshot) {
+    FLAGS_make_snapshot_threshold_offset = 0;
+    ::openmldb::tablet::TabletImpl* tablet = new ::openmldb::tablet::TabletImpl();
```
Comment (zhanghaohit) [inline src/replica/snapshot_replica_test.cc:221]: @dl239 the `tablet` here seems no need to be manually deleted, as we pass it as `brpc::SERVER_OWNS_SERVICE`.

Comment (dl239) [reply src/replica/snapshot_replica_test.cc:221]: ok

**Review by aceforeverd — APPROVED** [review]
