### PR TITLE
fix: sdk get all dbs

### LINKED ISSUE #3730: DBSDK::GetAllDbs() can't get the database with no table
https://github.com/4paradigm/OpenMLDB/blob/40eaf505167b98cf82de18aedb17a35d67023845/src/sdk/db_sdk.cc#L438
So create like hive will fail.
You can check it by:
create database empty_db;
create table empty_db.t1 like hive 'hive://t1'

### PR DESCRIPTION
**Pull request by vagetablechicken**
closes #3730

### CODE REVIEW

File: src/sdk/db_sdk.cc [hunk 1]
```diff
@@ -430,16 +430,20 @@ bool ClusterSDK::BuildCatalog() {
...
-        DLOG(INFO) << "no procedures in db";
+        LOG(INFO) << "no procedures in db";
     }
+    // The empty database can't be find if we only get table datas, but database no notify, so we get alldbs from
+    // nameserver in GetAllDbs()
     return UpdateCatalog(table_datas, sp_datas);
 }
 
 std::vector<std::string> DBSDK::GetAllDbs() {
     std::lock_guard<::openmldb::base::SpinMutex> lock(mu_);
```
Comment (vagetablechicken) [inline src/sdk/db_sdk.cc]: remove lock

**Review by dl239 — APPROVED** [review]

**Review by aceforeverd — APPROVED** [review]
