### PR TITLE
fix: support long window `count(*)`

### LINKED ISSUE #1654: support count(*) in pre-aggregation/long window
**Describe the feature you'd like**

Currently we only support aggregation over single column.

**Additional context**

long-window aggregation

### PR DESCRIPTION
**Pull request by nautaa**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix

* **What is the current behavior?** (You can also link to an open issue here)
close #1654

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

File: hybridse/src/vm/runner.cc [hunk 1]
```diff
@@ -2690,7 +2690,15 @@ bool RequestAggUnionRunner::InitAggregator() {
     }
 
     agg_type_ = type_it->second;
-    auto agg_col_type = producers_[1]->row_parser()->GetType(*agg_col_);
+    type::Type agg_col_type;
+    if (agg_col_->GetExprType() == node::kExprColumnRef) {
+        agg_col_type = producers_[1]->row_parser()->GetType(agg_col_name_);
+    } else if (agg_col_->GetExprType() == node::kExprAll) {
+        agg_col_type = type::Type::kInt64;
```
Comment (zhanghaohit) [inline hybridse/src/vm/runner.cc:2701]: double check if the `agg func` is `count`. otherwise log error and fail

File: src/storage/aggregator.cc [hunk 2]
```diff
@@ -72,12 +72,13 @@ Aggregator::Aggregator(const ::openmldb::api::TableMeta& base_meta, const ::open
...
             aggr_col_idx_ = i;
+            aggr_col_type_ = base_meta.column_desc(aggr_col_idx_).data_type();
         }
         if (base_meta.column_desc(i).name() == ts_col_) {
             ts_col_idx_ = i;
+            ts_col_type_ = base_meta.column_desc(ts_col_idx_).data_type();
         }
     }
-    aggr_col_type_ = base_meta.column_desc(aggr_col_idx_).data_type();
     ts_col_type_ = base_meta.column_desc(ts_col_idx_).data_type();
```
Comment (zhanghaohit) [inline src/storage/aggregator.cc]: you intend to remove this line?

**Review by zhanghaohit — CHANGES_REQUESTED** [review]

**Review by zhanghaohit — APPROVED** [review]

**Review by dl239 — APPROVED** [review]
