### PR TITLE
fix: a few minor bugs

### LINKED ISSUE #1335: DefaultUdfLibrary: wrong static initialization order
there is a static `DefaultUdfLibrary` instance https://github.com/4paradigm/OpenMLDB/blob/1aecdbc7f3bffe62373fecdab158f9f6611d9775/hybridse/src/udf/default_udf_library.h#L26, we get the static instance via `DefaultUdfLibrary::get`,  while in its initialization flow:

- constructor -> `DefaultUdfLibrary::Init` -> `RegisterNativeUdfToModule` -> `RegisterMethod` -> calls `DefaultUdfLibrary::get()`

it require the static instance while it is construction done

### LINKED ISSUE #1445: sql engine: recheck `PhysicalConstProjectNode::InitSchema`
`PhysicalConstProjectNode::InitSchema` InitFnDef with a function local `SchemaContext` that will invalided after `InitSchema`, which might fail codegen since FnInfo saved the `SchemaContext`. 

#1381 give a workaround fix but we might recheck and give a more well-designed solution.

### LINKED ISSUE #1522: resolve the dependency warning in java modules
**Bug Description**

Screenshot_20220323_082152_com android chrome

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

### PR DESCRIPTION
**Pull request by aceforeverd**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

1. close #1335 
2. close #1522 
3. close #1445 
4. refactor `start_onebox.sh`, resolve the issue e.g log directory not exists after component start

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

File: hybridse/src/udf/udf_library.h [hunk 1]
```diff
@@ -74,6 +74,10 @@ struct UdfLibraryEntry;
  */
 class UdfLibrary {
  public:
+    UdfLibrary() = default;
+    UdfLibrary(const UdfLibrary&) = delete;
```
Comment (dl239) [inline hybridse/src/udf/udf_library.h:78]: disable the copy assignment operators

**Review by vagetablechicken — APPROVED** [review]

**Review by zhanghaohit — APPROVED** [review]

**Comment by aceforeverd** [comment]
[High-priority Bugs (0.5.x)](https://trello.com/c/iGid67sw/70-high-priority-bugs-05x)

**Comment by aceforeverd** [comment]
[Bugs (0.5.x)](https://trello.com/c/WhbjlRN2/69-bugs-05x)
