### PR TITLE
fix: cleanup the usage of ts_name

### LINKED ISSUE #1907: Delete the `Get` function in tablet_client
`Get` function with `ts_name` in tablet_client is not used now. We should delete it from src/client/tablet_client.h and src/client/tablet_client.cc

- delete declaration in [header file](
https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.h#L104)
- delete the implement in [tablet_client.cc](https://github.com/4paradigm/OpenMLDB/blob/main/src/client/tablet_client.cc#L823)
-  don't pass `ts_name` in `HandleNSGet` function https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/openmldb.cc#L1486 https://github.com/4paradigm/OpenMLDB/blob/main/src/cmd/openmldb.cc#L1500

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Cleanup

* **What is the current behavior?** (You can also link to an open issue here)
Resolved #1907

* **What is the new behavior (if this is a feature change)?**
None

### CODE REVIEW

File: src/client/tablet_client.cc [hunk 1]
```diff
@@ -808,7 +808,7 @@ bool TabletClient::Get(uint32_t tid, uint32_t pid, const std::string& pk, uint64
 }
 
 bool TabletClient::Get(uint32_t tid, uint32_t pid, const std::string& pk, uint64_t time, const std::string& idx_name,
-                       const std::string& ts_name, std::string& value, uint64_t& ts, std::string& msg) {
+                       std::string& value, uint64_t& ts, std::string& msg) {
```
Comment (dl239) [inline src/client/tablet_client.cc:811]: hi @mangoGoForward take a look at the compile error https://github.com/4paradigm/OpenMLDB/runs/6704867176?check_suite_focus=true#step:7:256

Comment (dl239) [inline src/client/tablet_client.cc]: hi @mangoGoForward take a look at the compile error https://github.com/4paradigm/OpenMLDB/runs/6704867176?check_suite_focus=true#step:7:256

**Review by dl239 — APPROVED** [review]

**Review by vagetablechicken — APPROVED** [review]
