### PR TITLE
fix: snapshot recover for disk table

### LINKED ISSUE #2166: For a single node cluster, the disk table kreloadtableop fails after the tablet is restarted
**Bug Description**
For a single node cluster, restart the tablet after making a snapshot, and the disk table kreloadtableop fails

According to the log, it is roughly estimated that rename failed when making snapshot
企业微信截图_510b990f-6fd5-4028-a36c-0149be92905f
企业微信截图_5a0e6617-def3-4e5c-8069-11299d2411bd

**Expected Behavior**
The status of kreloadtableop is kdone

**Steps to Reproduce**
1. Deploy a single node cluster with only one ns and one tablet
2. Create SSD and HDD tables and insert 100 pieces of data
3. Execute make snapshot operation
4. Restart tablet
5. showopstatus

### PR DESCRIPTION
**Pull request by zhanghaohit**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix #2166

### CODE REVIEW

File: src/tablet/tablet_impl.cc [hunk 1]
```diff
@@ -3121,16 +3121,18 @@ int TabletImpl::LoadDiskTableInternal(uint32_t tid, uint32_t pid, const ::openml
...
             std::string snapshot_dir = snapshot_path + manifest.name();
-            PDLOG(INFO, "rename dir %s to %s. tid %u pid %u", snapshot_dir.c_str(), data_path.c_str(), tid, pid);
-            if (!::openmldb::base::Rename(snapshot_dir, data_path)) {
-                PDLOG(WARNING, "rename dir failed. tid %u pid %u path %s", tid, pid, snapshot_dir.c_str());
-                break;
-            }
-            if (unlink(manifest_file.c_str()) < 0) {
-                PDLOG(WARNING, "remove manifest failed. tid %u pid %u path %s", tid, pid, manifest_file.c_str());
-                break;
+            if (::openmldb::base::IsExists(snapshot_dir)) {
```
Comment (dl239) [inline src/tablet/tablet_impl.cc:3124]: why occurs that there is `MANIFEST` file but no snapshot dir

Comment (zhanghaohit) [reply src/tablet/tablet_impl.cc:3124]: one potential cause:
- re-start the tablet
- just after `rename` snapshot dir to `data`, but before `unlink` `MANIFEST`, stop tablet
- start the tablet: only `MANIFEST` exists, but the snapshot dir is not

Now the logic changes. We do a `hardlink` rather than `rename` in case some unexpected happens before following `MakeSnapshot`.

File: src/tablet/tablet_impl.cc [hunk 2]
```diff
@@ -3121,16 +3121,17 @@ int TabletImpl::LoadDiskTableInternal(uint32_t tid, uint32_t pid, const ::openml
...
+                PDLOG(INFO, "hardlink dir %s to %s. tid %u pid %u", snapshot_dir.c_str(), data_path.c_str(), tid, pid);
+                if (::openmldb::base::HardLinkDir(snapshot_dir, data_path)) {
+                    PDLOG(WARNING, "hardlink snapshot dir to data dir failed. tid %u pid %u path %s", tid, pid,
+                          snapshot_dir.c_str());
+                    break;
+                }
+                snapshot_offset = manifest.offset();
+            } else {
+                LOG(WARNING) << snapshot_dir << " is not exists";
```
Comment (dl239) [inline src/tablet/tablet_impl.cc]: it's better to add `tid` and `pid` to log message

**Review by dl239 — APPROVED** [review]

**Comment by zhanghaohit** [comment]
@wuyou10206 pls check and verify if this pr fixes the bug reported

**Review by wuyou10206 — APPROVED** [review]
