### PR TITLE
fix: write table meta file when update ttl

### LINKED ISSUE #1904: `Tablet` has not save `ttl` when updating the `ttl` of index
`Tablet` has not save `ttl` to `table_meta.txt` when updating the `ttl` of index

### PR DESCRIPTION
**Pull request by dl239**
fix the bug #1904

### CODE REVIEW

File: src/storage/table.cc [hunk 1]
```diff
@@ -152,14 +163,6 @@ void Table::UpdateTTL() {
...
         }
     }
-    auto table_meta = std::atomic_load_explicit(&table_meta_, std::memory_order_acquire);
-    auto new_table_meta = std::make_shared<::openmldb::api::TableMeta>(*table_meta);
-    new_table_meta->clear_column_key();
-    for (auto& index : indexs) {
-        auto column_key = new_table_meta->add_column_key();
-        column_key->CopyFrom(index->GenColumnKey());
-    }
-    std::atomic_store_explicit(&table_meta_, new_table_meta, std::memory_order_release);
```
Comment (zhanghaohit) [inline src/storage/table.cc:162]: no need to update the `table_meta_` in `UpdateTTL()`?

Comment (dl239) [reply src/storage/table.cc:162]: have moved to `SetTTL` function

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by zhanghaohit — APPROVED** [review]
